/**
 * 图标表 —— 用矢量图标取代此前的 emoji。
 *
 * 命名按「语义」而非「形状」：视图里写 `<AppIcon name="audio" />`，
 * 而不是 `<AppIcon name="music" />`，这样换图标不影响调用点。
 *
 * 图标一律继承 `currentColor`（lucide 默认行为），因此颜色仍由 tokens.css 决定，
 * 本文件与调用点都不出现色值。
 *
 * 用法：
 *   import AppIcon from '@/components/AppIcon.vue'
 *   <AppIcon name="assets" :size="16" />
 * 需要按名查找时（命令面板等）用 `ICONS[name]`。
 */
import type { Component } from 'vue'
import {
  Activity,
  Aperture,
  Archive,
  ArrowDownToLine,
  ArrowLeft,
  ArrowRight,
  ArrowUpDown,
  ArrowUpFromLine,
  Backpack,
  Ban,
  Binary,
  Bone,
  Book,
  BookMarked,
  BookOpen,
  Boxes,
  Braces,
  Bug,
  Calculator,
  CalendarClock,
  ChartNoAxesColumn,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CircleDot,
  CircleHelp,
  CircleMinus,
  CirclePlus,
  CircleStop,
  CircleX,
  Clipboard,
  Clock,
  Code,
  Command,
  Compass,
  Copy,
  Crosshair,
  Database,
  Download,
  Drama,
  Droplet,
  Eraser,
  ExternalLink,
  Eye,
  File,
  FileCode2,
  FileJson,
  FilePlus,
  FileText,
  FileWarning,
  Filter,
  Flag,
  Flame,
  Folder,
  FolderCog,
  FolderOpen,
  Gauge,
  Gem,
  Globe,
  Grid2x2,
  Hammer,
  Hash,
  Heart,
  Home,
  Hourglass,
  Image,
  Info,
  Keyboard,
  Key,
  Layers,
  LayoutGrid,
  Lightbulb,
  Link,
  List,
  ListTree,
  Loader,
  Lock,
  Map,
  MapPin,
  Maximize2,
  Megaphone,
  Menu,
  Minus,
  Monitor,
  Moon,
  MoreHorizontal,
  MousePointerClick,
  Move,
  Music,
  Package,
  PackageOpen,
  Paintbrush,
  Palette,
  PanelLeft,
  PanelRight,
  Pause,
  Pencil,
  Pipette,
  Play,
  Plus,
  Power,
  Radar,
  RefreshCw,
  Replace,
  Rocket,
  RotateCcw,
  Rows3,
  Ruler,
  Save,
  ScanSearch,
  Search,
  Settings,
  ShieldAlert,
  ShieldCheck,
  SkipBack,
  SkipForward,
  Skull,
  SlidersHorizontal,
  Sparkles,
  Split,
  Square,
  SquareStack,
  Star,
  Sun,
  Swords,
  Table2,
  Tag,
  Target,
  Terminal,
  Timer,
  Trash2,
  TreePine,
  TriangleAlert,
  Type,
  Undo2,
  Upload,
  User,
  Users,
  Volume2,
  VolumeX,
  Wand2,
  Waves,
  Wifi,
  WifiOff,
  Wind,
  Wrench,
  X,
  Zap,
  ZoomIn,
  ZoomOut,
} from 'lucide-vue-next'

export const ICONS = {
  // ── 模块 / 工作台 ──
  assets: Package,
  audio: Music,
  text: FileText,
  staticData: Table2,
  export: Upload,
  project: FolderCog,
  settings: Settings,
  help: CircleHelp,
  wiki: BookOpen,
  library: Book,

  // ── 维基分类 ──
  wikiOverview: Globe,
  wikiPersona: Drama,
  wikiEnemy: Skull,
  wikiAbnormality: Aperture,
  wikiEgo: Swords,
  wikiEgoGift: Gem,
  wikiAnnouncer: Megaphone,
  wikiStory: BookMarked,
  wikiStage: Map,
  wikiItem: Backpack,
  wikiMechanism: Wrench,
  wikiKeyword: Key,
  wikiSpine: Bone,

  // ── 导航 / 结构 ──
  home: Home,
  folder: Folder,
  folderOpen: FolderOpen,
  file: File,
  fileCode: FileCode2,
  fileJson: FileJson,
  fileAdd: FilePlus,
  layers: Layers,
  list: List,
  listTree: ListTree,
  tree: TreePine,
  grid: Grid2x2,
  rows: Rows3,
  panelLeft: PanelLeft,
  panelRight: PanelRight,
  menu: Menu,
  split: Split,
  stack: SquareStack,
  boxes: Boxes,

  // ── 操作 ──
  search: Search,
  scanSearch: ScanSearch,
  filter: Filter,
  sort: ArrowUpDown,
  refresh: RefreshCw,
  save: Save,
  copy: Copy,
  paste: Clipboard,
  trash: Trash2,
  edit: Pencil,
  plus: Plus,
  minus: Minus,
  close: X,
  check: Check,
  undo: Undo2,
  erase: Eraser,
  replace: Replace,
  download: Download,
  upload: Upload,
  externalLink: ExternalLink,
  link: Link,
  open: PackageOpen,
  run: Play,
  wand: Wand2,
  target: Target,
  crosshair: Crosshair,
  scan: Radar,
  maximize: Maximize2,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  pipette: Pipette,
  ruler: Ruler,
  brush: Paintbrush,
  hammer: Hammer,
  move: Move,
  click: MousePointerClick,

  // ── 播放控制 ──
  play: Play,
  pause: Pause,
  stop: CircleStop,
  stopSquare: Square,
  skipBack: SkipBack,
  skipForward: SkipForward,
  volume: Volume2,
  mute: VolumeX,

  // ── 方向 ──
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  more: MoreHorizontal,

  // ── 状态 / 反馈 ──
  success: CircleCheck,
  error: CircleAlert,
  warning: TriangleAlert,
  info: Info,
  danger: ShieldAlert,
  blocked: Ban,
  stopCircle: CircleStop,
  dot: CircleDot,
  dotPlus: CirclePlus,
  dotMinus: CircleMinus,
  loader: Loader,
  activity: Activity,
  clock: Clock,
  timer: Timer,
  hourglass: Hourglass,
  gauge: Gauge,
  chart: ChartNoAxesColumn,
  database: Database,
  power: Power,
  wifi: Wifi,
  wifiOff: WifiOff,
  lock: Lock,
  shieldCheck: ShieldCheck,
  warningFile: FileWarning,

  // ── 内容 / 提示 ──
  hint: Lightbulb,
  guide: Compass,
  sparkles: Sparkles,
  star: Star,
  heart: Heart,
  bookmark: Flag,
  pin: MapPin,
  tag: Tag,
  hash: Hash,
  type: Type,
  keyboard: Keyboard,
  command: Command,
  terminal: Terminal,
  code: Code,
  braces: Braces,
  binary: Binary,
  calculator: Calculator,
  monitor: Monitor,
  image: Image,
  calendar: CalendarClock,
  users: Users,
  user: User,
  sliders: SlidersHorizontal,
  wrench: Wrench,
  bug: Bug,
  rocket: Rocket,
  language: Globe,
  archive: Archive,
  downToLine: ArrowDownToLine,
  upFromLine: ArrowUpFromLine,
  flame: Flame,
  zap: Zap,
  wind: Wind,
  droplet: Droplet,
  waves: Waves,

  // ── 外观 ──
  sun: Sun,
  moon: Moon,
  palette: Palette,
} as const satisfies Record<string, Component>

export type IconName = keyof typeof ICONS

/** 图标名清单（设置页 / 自检页展示用） */
export const ICON_NAMES = Object.keys(ICONS) as IconName[]
